=== Mate74/kvnnoo_xmlgyak/KVNNOO_1005/DMT_ertoxsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="minta">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="A"  maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Ab"  maxOccurs="unbounded" >
									<xs:complexType>
										<xs:sequence>
											<xs:element name="Abx" type="xs:string" />
											<xs:element name="Aby" type="xs:string" />
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="Ac"  maxOccurs="unbounded" >
									<xs:complexType>
										<xs:sequence>
											<xs:element name="Acd" type="xs:string" />
											<xs:element name="Ace" type="xs:string" />
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="Aa" type="xs:int" use="required" />							
						</xs:complexType>
					</xs:element>
					<xs:element name="B"  maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Bb"  >
									<xs:complexType>
										<xs:sequence>
											<xs:element name="Bbx" type="xs:string" />
											<xs:element name="Bby" type="xs:string" />
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="Ba" type="xs:int" use="required" />
							<xs:attribute name="Bc" type="xs:int" use="optional" />							
						</xs:complexType>
					</xs:element>
					<xs:element name="C"  maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Cb" type="xs:string" />
							</xs:sequence>
							<xs:attribute name="Ca" type="xs:int" use="required" />				
						</xs:complexType>
					</xs:element>
					<xs:element name="A_B"  maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="A_Bc" type="xs:string"  />
							</xs:sequence>
							<xs:attribute name="A_B_a" type="xs:int" use="optional" />
							<xs:attribute name="A_B_b" type="xs:int" use="optional" />							
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
</xs:schema>

=== Mate74/kvnnoo_xmlgyak/KVNNOO_1005/DMT_xsdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>

<minta     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="DMT_ertoxsd.xsd">
	<A Aa="01">
		<Ab>
			<Abx>
			haha
			</Abx>
			<Aby>
			hahaha
			</Aby>
		</Ab>
		<Ac>
			<Acd>
			József
			</Acd>
			<Ace>
			Balázs
			</Ace>
		</Ac>
	</A>
	<B Ba="01" Bc="01">
		<Bb>
			<Bbx>
			Kossuth
			</Bbx>
			<Bby>
			Lajos
			</Bby>
		</Bb>
	</B>
	<C Ca="01">
		<Cb>
		hahahahahaha
		</Cb>
	</C>
	<A_B A_B_a="01" A_B_b="01">
		<A_Bc>
		nagyon jó
		</A_Bc>
	</A_B>
</minta>
