=== Mate74/kvnnoo_xmlgyak/XMLTaskKVNNOO/XMLSchemaKVNNOO.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:complexType name="AruType">
	<xs:sequence>
		<xs:element name="Elektronikai_cikkek">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="Televizio" type="xs:string" />
					<xs:element name="Mikorhullamu_suto" type="xs:string" />
					<xs:element name="Mosogep" type="xs:string"  />
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="Szamitastechnikai_eszkozok">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="Laptop" type="xs:string"  />
					<xs:element name="Mobiltelefon" type="xs:string"  />
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="Bnev" type="xs:string" />
	</xs:sequence>
		<xs:attribute name="Azonosito" type="xs:int" use="required" />
</xs:complexType>

<xs:complexType name="VasarloType">
	<xs:sequence>
		<xs:element name="Bankszamlaszam" type="xs:integer"  />
		<xs:element name="Szuletesi_ev" type="xs:integer"  />
		<xs:element name="Utel.szam" type="telefonType"  />
	</xs:sequence>
		<xs:attribute name="Vnev" type="xs:string" use="required" />
</xs:complexType>

<xs:complexType name="UgyfelszolgalatType">
	<xs:sequence>
		<xs:element name="UE-mail" type="emailType"  />
	</xs:sequence>
		<xs:attribute name="Utel.szam" type="telefonType" use="required" />
</xs:complexType>

<xs:complexType name="FutarszolgalatType">
	<xs:sequence>
		<xs:element name="FE-mail" type="emailType"  />
		<xs:element name="Bnev" type="xs:string" />
	</xs:sequence>
		<xs:attribute name="Ftel.szam" type="telefonType" use="required" />
</xs:complexType>

<xs:simpleType name="emailType">
	<xs:restriction base="xs:string">
		<xs:pattern value="[\w.]+@\w+\.\w+"/>
	</xs:restriction>
</xs:simpleType>
	
<xs:simpleType name="telefonType">
	<xs:restriction base="xs:string">
		<xs:pattern value="\06\d{1,2}\d{3}\d{4}"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="BoltType">
	<xs:sequence>
		<xs:element name="Alkalmazottak">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="Alkalmazott" type="xs:string" maxOccurs="unbounded"  />
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="Alapitasi_ev" type="xs:integer"  />
	</xs:sequence>
		<xs:attribute name="Bnev" type="xs:string" use="required" />
</xs:complexType>

<xs:complexType name="VasarlasType">
	<xs:sequence>
		<xs:element name="Azonosito" type="xs:string"  />
		<xs:element name="Vnev" type="xs:string"  />
	</xs:sequence>
</xs:complexType>

<xs:element name="Boltok_mukodesi_elve">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Aru" type="AruType" maxOccurs="unbounded" />
			<xs:element name="Vasarlo" type="VasarloType" maxOccurs="unbounded" />
			<xs:element name="Ugyfelszolgalat" type="UgyfelszolgalatType" maxOccurs="unbounded" />
			<xs:element name="Futarszolgalat" type="FutarszolgalatType" maxOccurs="unbounded" />
			<xs:element name="Bolt" type="BoltType" maxOccurs="unbounded" />
			<xs:element name="Vasarlas" type="VasarlasType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<!-- Keys -->
	<xs:key name="key1">
		<xs:selector xpath="Aru"/>
		<xs:field xpath="@Azonosito"/>
	</xs:key>
	
	<xs:key name="key2">
		<xs:selector xpath="Vasarlo"/>
		<xs:field xpath="@Vnev"/>
	</xs:key>
	
	<xs:key name="key3">
		<xs:selector xpath="Ugyfelszolgalat"/>
		<xs:field xpath="@Utel.szam"/>
	</xs:key>
	
	<xs:key name="key4">
		<xs:selector xpath="Futarszolgalat"/>
		<xs:field xpath="@Ftel.szam"/>
	</xs:key>
	
	<xs:key name="key5">
		<xs:selector xpath="Bolt"/>
		<xs:field xpath="@Bnev"/>
	</xs:key>
	
	<xs:keyref name="keyref1" refer="key5">
		<xs:selector xpath="Aru/Bnev"/>
		<xs:field xpath="@Bnev"/>
	</xs:keyref>
	
	<xs:keyref name="keyref2" refer="key1">
		<xs:selector xpath="Vasarlas/Azonosito"/>
		<xs:field xpath="@Azonosito"/>
	</xs:keyref>
	
	<xs:keyref name="keyref3" refer="key2">
		<xs:selector xpath="Vasarlas/Vnev"/>
		<xs:field xpath="@Vnev"/>
	</xs:keyref>
	
	<xs:keyref name="keyref4" refer="key3">
		<xs:selector xpath="Vasarlo/Utel.szam"/>
		<xs:field xpath="@Utel.szam"/>
	</xs:keyref>
	
	<xs:keyref name="keyref5" refer="key5">
		<xs:selector xpath="Futarszolgalat/Bnev"/>
		<xs:field xpath="@Bnev"/>
	</xs:keyref>
	
</xs:element>
</xs:schema>

=== Mate74/kvnnoo_xmlgyak/XMLTaskKVNNOO/XMLKVNNOO.xml
<?xml version="1.0" encoding="UTF-8"?>
<Boltok_mukodesi_elve     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="XMLSchemaKVNNOO.xsd">
            <Aru Azonosito="01">
            	<Elektronikai_cikkek>
            		<Televizio>Samsung</Televizio>
            		<Mikorhullamu_suto>Panasonic</Mikorhullamu_suto>
            		<Mosogep>Whirlpool</Mosogep>
            	</Elektronikai_cikkek>
            	<Szamitastechnikai_eszkozok>
            		<Laptop>Lenovo</Laptop>
            		<Mobiltelefon>Iphone</Mobiltelefon>
            	</Szamitastechnikai_eszkozok>
            	<Bnev>METRO</Bnev>
            </Aru>
            
            <Aru Azonosito="02">
            	<Elektronikai_cikkek>
            		<Televizio>LG</Televizio>
            		<Mikorhullamu_suto>Elektrolux</Mikorhullamu_suto>
            		<Mosogep>BOSCH</Mosogep>
            	</Elektronikai_cikkek>
            	<Szamitastechnikai_eszkozok>
            		<Laptop>ASUS</Laptop>
            		<Mobiltelefon>Huaweii</Mobiltelefon>
            	</Szamitastechnikai_eszkozok>
            	<Bnev>Elektrolux</Bnev>
            </Aru>
         
            <Aru Azonosito="03">
            	<Elektronikai_cikkek>
            		<Televizio>Phillips</Televizio>
            		<Mikorhullamu_suto>Samsung</Mikorhullamu_suto>
            		<Mosogep>Siemens</Mosogep>
            	</Elektronikai_cikkek>
            	<Szamitastechnikai_eszkozok>
            		<Laptop>HP</Laptop>
            		<Mobiltelefon>Nokia</Mobiltelefon>
            	</Szamitastechnikai_eszkozok>
            	<Bnev>Media_Markt</Bnev>
            </Aru>
            
            <Vasarlo Vnev="Mengyan Máté">
            	<Bankszamlaszam>1171234567891011</Bankszamlaszam>
            	<Szuletesi_ev>1999</Szuletesi_ev>
            	<Utel.szam>06201234567</Utel.szam>
            </Vasarlo>
            
            <Vasarlo Vnev="Deák Tivadar">
            	<Bankszamlaszam>1171011987654321</Bankszamlaszam>
            	<Szuletesi_ev>2010</Szuletesi_ev>
            	<Utel.szam>06709876543</Utel.szam>
            </Vasarlo>
            
            <Vasarlo Vnev="Csehi Beáta">
            	<Bankszamlaszam>1171234987651110</Bankszamlaszam>
            	<Szuletesi_ev>2004</Szuletesi_ev>
            	<Utel.szam>06309871234</Utel.szam>
            </Vasarlo>
            
            <Ugyfelszolgalat Utel.szam="06209875463">
            	<UE-mail>metro@gmail.com</UE-mail>
            </Ugyfelszolgalat>
            
  			<Ugyfelszolgalat Utel.szam="06309997777">
            	<UE-mail>electrolux@gmail.com</UE-mail>
            </Ugyfelszolgalat>
            
  			<Ugyfelszolgalat Utel.szam="06701112222">
            	<UE-mail>media.markt@gmail.com</UE-mail>
            </Ugyfelszolgalat>
            
            <Futarszolgalat Ftel.szam="06705897412">
            	<FE-mail>sprinter@gmail.com</FE-mail>
            	<Bnev>METRO</Bnev>
            </Futarszolgalat>
            
            <Futarszolgalat Ftel.szam="06208795462">
            	<FE-mail>furge.futar@gmail.com</FE-mail>
            	<Bnev>Electrolux</Bnev>
            </Futarszolgalat>
            
            <Futarszolgalat Ftel.szam="06201045030">
            	<FE-mail>furge.futar@gmail.com</FE-mail>
            	<Bnev>Media_Markt</Bnev>
            </Futarszolgalat>
            
            <Bolt Bnev="METRO">
            <Alkalmazottak>
            	<Alkalmazott>Sándor Béla</Alkalmazott>
            	<Alkalmazott>Táglás Tibor</Alkalmazott>
            	<Alkalmazott>Lakatos Lajos</Alkalmazott>
            </Alkalmazottak>
            <Alapitasi_ev>1985</Alapitasi_ev>
            </Bolt>
            
            <Bolt Bnev="Elektrolux">
            <Alkalmazottak>
            	<Alkalmazott>Horváth László</Alkalmazott>
            	<Alkalmazott>Péter Károly</Alkalmazott>
            	<Alkalmazott>Kovács Boglárka</Alkalmazott>
            </Alkalmazottak>
            <Alapitasi_ev>1965</Alapitasi_ev>
            </Bolt>
            
            <Bolt Bnev="Media_Markt">
            <Alkalmazottak>
            	<Alkalmazott>Szabó Réka</Alkalmazott>
            	<Alkalmazott>Tiszlavits Gergő</Alkalmazott>
            	<Alkalmazott>Pázmány István</Alkalmazott>
            </Alkalmazottak>
            <Alapitasi_ev>1965</Alapitasi_ev>
            </Bolt>
            
   			<Vasarlas>
   				<Azonosito>01</Azonosito>
   				<Vnev>Mengyan Máté</Vnev>
   			</Vasarlas>

   			<Vasarlas>
   				<Azonosito>02</Azonosito>
   				<Vnev>Deák Tivadar</Vnev>
   			</Vasarlas>
   			
   			<Vasarlas>
   				<Azonosito>03</Azonosito>
   				<Vnev>Csehi Beáta</Vnev>
   			</Vasarlas>
</Boltok_mukodesi_elve>
