=== Mate74/kvnnoo_xmlgyak/KVNNOO_1013/DMT_konyv_mod.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="konyvek">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="konyv" type="konyvTipus" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	</xs:element>
	<xs:complexType name="konyvTipus">
		<xs:sequence>
			<xs:element name="cim" type="xs:string"/>
			<xs:element name="szerzo" type="xs:string" />
			<xs:element ref="szereplo" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="szereplo"  >
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nev" type="xs:string" maxOccurs="unbounded" />
				<xs:element name="baratja" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="szuletett" type="szuletettTipus" maxOccurs="unbounded"  />
				<xs:element name="jellemzÃ©s" type="xs:string" maxOccurs="unbounded"  />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="szuletettTipus">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1950"/>
			<xs:maxInclusive value="2000"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Mate74/kvnnoo_xmlgyak/KVNNOO_1013/DMT_konyv1.xml
<?xml version="1.0" encoding="UTF-8"?>

<konyvek   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="DMT_konyv_mod.xsd">
	<konyv>
		<cim>
		asdasdsadas
		</cim>
		<szerzo>
		sadasdasdas
		</szerzo>
		<szereplo>
			<nev>
			asdasdasd
			</nev>
			<baratja>
			dsadasdas
			</baratja>
			<szuletett>
			1988
			</szuletett>
			<jellemzÃ©s>
			asdasdasd
			</jellemzÃ©s>
		</szereplo>
		<szereplo>
			<nev>
			asdadasd
			</nev>
			<szuletett>
			1977
			</szuletett>
			<jellemzÃ©s>
			asdasdasda
			</jellemzÃ©s>
		</szereplo>
	</konyv>
</konyvek>
