=== Mate74/kvnnoo_xmlgyak/KVNNOO_1013/DMT_nevjegykartya.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="nevjegykartyak">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="nevjegykartya" type="nevjegykartyaTipus" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:complexType name="nevjegykartyaTipus">
	<xs:sequence>
		<xs:element name="nev" type="xs:string"/>
		<xs:element name="ceg" type="cegTipus" />
		<xs:element name="beosztas" type="beosztasTipus" />
		<xs:element name="telefonszam" type="xs:integer" />
		<xs:element name="email" type="xs:string" />
	</xs:sequence>
</xs:complexType>
<xs:complexType name="cegTipus">
	<xs:sequence>
		<xs:element name="nev" type="xs:string" />
		<xs:element name="cim" type="cimTipus" />
		<xs:element name="telefonszam"  type="xs:integer"/>
		<xs:element name="weblap" type="xs:string" />
	</xs:sequence>
</xs:complexType>
<xs:complexType name="cimTipus">
	<xs:sequence>
		<xs:element name="iranyitoszam" type="xs:int" />
			<xs:element name="varos" type="xs:string" />
		<xs:element name="utca"  type="xs:string"/>
		<xs:element name="hazszam" type="xs:int" />
	</xs:sequence>
</xs:complexType>
<xs:simpleType name="beosztasTipus">
	<xs:restriction base="xs:string">
		<xs:enumeration value="fonok" />
		<xs:enumeration value="alkalmazott" />
	</xs:restriction>
</xs:simpleType>
</xs:schema>

=== Mate74/kvnnoo_xmlgyak/KVNNOO_1013/DMT_nevjegykartya.xml
<?xml version="1.0" encoding="UTF-8"?>

<nevjegykartyak    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="DMT_nevjegykartya.xsd">
	<nevjegykartya >
		<nev>
			Deák Máté Tibor
		</nev>
		<ceg>
			<nev>
			Miskolci Egyetem
			</nev>
			<cim>
				<iranyitoszam>
				3515
				</iranyitoszam>
				<varos>
				Miskolc
				</varos>
				<utca>
				Miskolc-egyetemváros
				</utca>
				<hazszam>
				12
				</hazszam>
			</cim>
			<telefonszam>
			0646565111
			</telefonszam>
			<weblap>
			https://www.uni-miskolc.hu
			</weblap>
		</ceg>
		<beosztas>
		Programmtervező Informatikus
		</beosztas>
		<telefonszam>
		06203642970
		</telefonszam>
		<email>
		mate.deak99@gmail.com
		</email>

	</nevjegykartya>
            
</nevjegykartyak>

=== Mate74/kvnnoo_xmlgyak/KVNNOO_1110/DMT_nevjegykartya.xml
<?xml version="1.0" encoding="UTF-8"?>

<nevjegykartyak    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="DMT_nevjegykartya.xsd">
	<nevjegykartya>
		<nev>
			Deák Máté Tibor
		</nev>
		<ceg>
			<nev>
			Obi
			</nev>
			<cim>
				<iranyitoszam>
				3712
				</iranyitoszam>
				<varos>
				Miskolc
				</varos>
				<utca>
				Kertész utca
				</utca>
				<hazszam>
				10
				</hazszam>
			</cim>
			<telefonszam>06707779998</telefonszam>
			<weblap>
			Obi.hu
			</weblap>
		</ceg>
		<beosztas>fonok</beosztas>
		<telefonszam>06204444555</telefonszam>
		<email>
		nincs.email@gmail.com
		</email>
	</nevjegykartya>
	<nevjegykartya>
		<nev>
			Halász László
		</nev>
		<ceg>
			<nev>
			Tesco
			</nev>
			<cim>
				<iranyitoszam>
				3712
				</iranyitoszam>
				<varos>
				Miskolc
				</varos>
				<utca>
				Kertész utca
				</utca>
				<hazszam>
				11
				</hazszam>
			</cim>
			<telefonszam>06705555888</telefonszam>
			<weblap>
			tesco.com
			</weblap>
		</ceg>
		<beosztas>alkalmazott</beosztas>
		<telefonszam>06203333777</telefonszam>
		<email>
		neki.sincs@gmail.com
		</email>
	</nevjegykartya>
            
</nevjegykartyak>
